data1<-read.csv("C:\\Users\\ACER\\Downloads\\household_power_consumption.txt",sep=";")
data2<-rbind(data1[as.character(data1$Date)=="1/2/2007",],data1[as.character(data1$Date)=="2/2/2007",])
data2$DateTime <- paste(as.character(data2$Date), as.character(data2$Time))
data2$DateTime <- strptime(data2$DateTime, format = "%d/%m/%Y %H:%M:%S")
par(mfcol = c(2,2))
plot(data2$DateTime,as.numeric(as.character(data2[,3])),type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(data2$DateTime,as.numeric(as.character(data2[,7])),type="l",xlab="",ylab="Energy sub metering")
lines(data2$DateTime,as.numeric(as.character(data2[,8])),col="red")
lines(data2$DateTime,as.numeric(as.character(data2[,9])),col="blue")
legend("topright", lty=1, col=c("black","red","blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty="n")
plot(data2$DateTime,as.numeric(as.character(data2[,5])),type="l",xlab="datetime",ylab="Voltage")
plot(data2$DateTime,as.numeric(as.character(data2[,4])),type="l",xlab="datetime",ylab="Global_reactive_power")
dev.copy(png, file = "plot4.png")
dev.off()
